---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Dependency Submission

"on":
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '44 4 * * 2'

permissions: {}

jobs:
  dependency-submission:
    name: Submit gradle dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write # see action's documentation
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Configure tools
        uses: ./.github/actions/prepare-for-build

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1
        env:
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: "(?i)(^|:)(compileClasspath|runtimeClasspath|testCompileClasspath|testRuntimeClasspath)$"
          DEPENDENCY_GRAPH_EXCLUDE_CONFIGURATIONS: "(?i)(^|:)(classpath|.*PluginClasspath|kotlinCompilerClasspath|kaptClasspath|annotationProcessor|detachedConfiguration.*)$"
          DEPENDENCY_GRAPH_RUNTIME_INCLUDE_CONFIGURATIONS: "(?i)(^|:)runtimeClasspath$"
          DEPENDENCY_GRAPH_RUNTIME_EXCLUDE_CONFIGURATIONS: "(?i)(^|:)testRuntimeClasspath$"
